### PR TITLE
Add documentation and tests

### PR DESCRIPTION
**Pull request by louy**

### CODE REVIEW

**Comment by louy** [comment]
Basically I'm merging my repository into this one. Also please enable Travis CI on this repo.

**Comment by rapropos** [comment]
browser.d.ts was removed due to [this discussion](https://github.com/typings/registry/pull/86). I appreciate the effort you put into this, but it's basically a complete teardown and reimplementation, and I don't feel comfortable maintaining what is totally your code. If @blakeembrey decides your implementation is preferable, perhaps a better way to handle this is to point the typings registry at it instead.

**Comment by louy** [comment]
Cool. I've removed browser version.

It's true that it's a complete rewrite, but it's eventually the same (except for removing `Uint8Array` and adding `Buffer`, docs and tests)
I'm happy to maintain it. I just didn't want to have two repos as per @blakeembrey's request. We can move this to [typed-typings](https://github.com/typed-typings/) if you want.

**Comment by blakeembrey** [comment]
We could certainly transfer it to @typed-typings, if that works for both of you (you should both have access to it, of course). The changes do look great 👍 

Aside from that, on the `browser.d.ts` point. I now saw the removing `Buffer` change to make `browser.d.ts` a thing and that makes sense as an improvement too 👍 

Great work! I've used these typings in the past 😄

**Comment by louy** [comment]
OK then. I'll restore the browser file. I'm happy with moving this to @typed-typings.

Just to weigh in on browser declarations: to me browser environment has nothing to do with globals. I always use webpack for bundling scripts and never concatenate or import them using `<script>` tags.

IMO the difference between main and browser declarations is not the way they're exported, but the features they include. I guess the best example is this module which supports `Buffer` in node but not in browsers.

I believe using globals is a horrible practice, and browsers are not an exception.

**Comment by rapropos** [comment]
So what should I do to facilitate the move to @typed-typings?

**Comment by blakeembrey** [comment]
@rapropos I sent you an invite, just accept and transfer the repo. We'll update the registry afterwards.

@louy That's exactly the use-case for the `browser` in Typings - it's meant to follow the `browser` field specification (since TypeScript does not support it yet, I needed to hack the resolution into Typings).

**Comment by rapropos** [comment]
Hopefully the transfer worked.

**Comment by blakeembrey** [comment]
LGTM 👍

**Comment by louy** [comment]
Reopened as #4.

**Comment by rapropos** [comment]
@blakeembrey: does it make sense for me to transfer the [markdown-it](https://github.com/rapropos/typed-markdown-it) and [linkify-it](https://github.com/rapropos/typed-linkify-it) repos to @typed-typings as well?

**Comment by blakeembrey** [comment]
@rapropos Entirely your call to make, since you can move them.

**Pull request closed without merging**
